Repository maidsafe/safe-authenticator-mobile, pull requests merged in 2019-08, with the labels that each got.

#148 chore/bindings: update to use safe_authenticator v0.9.1 libs
  CakeScripts/IOSTest.cake
  CakeScripts/NativeLibs.cake
  README.md
Labels: Don't Merge !!!

#150 fix/iOS: Update iOS build from iPhone/iPad to universal
  .gitignore
  SafeAuthenticator.iOS/Info.plist
Labels: e/S :clock12:, enhancement, iOS, p/minor

#151 chore/authenticator: update packages for app and test projects
  CodeStyles.targets
  SafeAuthenticator.Android/Helpers/AndroidNativeBrowserService.cs
  SafeAuthenticator.Android/Helpers/AndroidNativeProgressDialogService.cs
  SafeAuthenticator.Android/Helpers/AppHandler.cs
  SafeAuthenticator.Android/Helpers/EntryMoveNextEffect.cs
  SafeAuthenticator.Android/Helpers/FileOps.cs
  SafeAuthenticator.Android/Helpers/GradientContentViewRenderer.cs
  SafeAuthenticator.Android/Helpers/MaterialEntryRenderer.cs
  SafeAuthenticator.Android/MainActivity.cs
  SafeAuthenticator.Android/SafeAuthenticator.Android.csproj
  SafeAuthenticator.Android/app.config
  SafeAuthenticator.iOS/AppDelegate.cs
  SafeAuthenticator.iOS/Extensions/FontExtensions.cs
  SafeAuthenticator.iOS/Helpers/AppHandler.cs
  SafeAuthenticator.iOS/Helpers/AppleNativeBrowserService.cs
  SafeAuthenticator.iOS/Helpers/AppleNativeProgressDialogService.cs
  SafeAuthenticator.iOS/Helpers/CustomScrollViewRenderer.cs
  SafeAuthenticator.iOS/Helpers/EntryMoveNextEffect.cs
  SafeAuthenticator.iOS/Helpers/FileOps.cs
  SafeAuthenticator.iOS/Helpers/GradientContentViewRenderer.cs
  SafeAuthenticator.iOS/Helpers/MaterialEntryRenderer.cs
  SafeAuthenticator.iOS/Helpers/ShowHidePasswordEffect.cs
  SafeAuthenticator.iOS/SafeAuthenticator.iOS.csproj
  SafeAuthenticator/App.xaml.cs
  SafeAuthenticator/SafeAuthenticator.csproj
  SafeAuthenticator/Views/SettingsPage.xaml.cs
  Tests/SafeAuth.Tests.Android/SafeAuth.Tests.Android.csproj
  Tests/SafeAuth.Tests.IOS/SafeAuth.Tests.IOS.csproj
Labels: Chore/CI, e/M :clock3:, p/major

#152 refactor:Update UI to improve the experience on big screen devices
  SafeAuthenticator/Controls/ContainerPermissionViewCell.xaml
  SafeAuthenticator/Controls/MDataPermissionViewCell.xaml
  SafeAuthenticator/Controls/RegisteredAppViewCell.xaml
Labels: bug, enhancement

#153 fix/solution: disable test projects build for iPhone Release configuration
  SafeAuthenticator.sln
Labels: Chore/CI, iOS
